options:
  logging: CLOUD_LOGGING_ONLY
  # Enable build cache
  machineType: 'E2_HIGHCPU_8'
  dynamicSubstitutions: true

steps:
  # Configure docker auth
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev']

  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/backend'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/backend'
      - '.'
  
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/frontend'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=http://localhost:8080'
      - '.'
  
  # Push the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/backend']
  
  # Push the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/frontend']
  
  # Deploy to Cloud Run with sidecar pattern
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'docubot-service'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--execution-environment'
    - 'gen2'
    - '--container'
    - 'frontend'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/frontend'
    - '--port'
    - '3000'
    - '--command'
    - 'node'
    - '--args'
    - 'server.js'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_API_URL=http://localhost:8080'
    - '--container'
    - 'backend'
    - '--image'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/backend'
    - '--set-env-vars'
    - 'PORT=8080,PYTHONPATH=/app/src'
    - '--cpu'
    - '1'
    - '--memory'
    - '1Gi'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/backend'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/docubot-repo/frontend'
