options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

steps:
  # VPCとサブネットの作成（存在しない場合のみ）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud compute networks describe vpc-direct-egress 2>/dev/null; then
          gcloud compute networks create vpc-direct-egress --subnet-mode=custom
          gcloud compute networks subnets create subnet-direct-egress \
            --network=vpc-direct-egress \
            --region=us-central1 \
            --range=10.10.0.0/28 \
            --enable-private-ip-google-access
        fi

  # サービスアカウントの作成（存在しない場合のみ）
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud iam service-accounts describe backend-sa@$PROJECT_ID.iam.gserviceaccount.com 2>/dev/null; then
          gcloud iam service-accounts create backend-sa --display-name="Backend Service Account"
        fi
        if ! gcloud iam service-accounts describe frontend-sa@$PROJECT_ID.iam.gserviceaccount.com 2>/dev/null; then
          gcloud iam service-accounts create frontend-sa --display-name="Frontend Service Account"
        fi

  # Configure docker auth
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['auth', 'configure-docker', 'us-central1-docker.pkg.dev']

  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:latest', '-f', 'backend/Dockerfile', 'backend/']

  # Build frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:latest', '-f', 'frontend/Dockerfile', 'frontend/']

  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:latest']

  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:latest']

  # Deploy backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'backend.yaml'
      - '--region'
      - 'us-central1'

  # Get backend URL and update frontend.yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe backend-service --region us-central1 --format='value(status.url)')
        sed -i "s|BACKEND_URL_PLACEHOLDER|$BACKEND_URL|g" frontend.yaml

  # IAM設定：フロントエンドにバックエンドへのアクセス権限を付与
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services add-iam-policy-binding backend-service \
          --member="serviceAccount:frontend-sa@$PROJECT_ID.iam.gserviceaccount.com" \
          --role="roles/run.invoker" \
          --region=us-central1

  # Deploy frontend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'frontend.yaml'
      - '--region'
      - 'us-central1'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/backend-repo/backend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/frontend-repo/frontend:latest'
