options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', '.']
  
  # Build the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', '.']
  
  # Push the backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']
  
  # Push the frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']
  
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/backend'
    - '--region'
    - 'asia-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
  
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'frontend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/frontend'
    - '--region'
    - 'asia-east1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'NEXT_PUBLIC_API_URL=https://backend-xxxxx-an.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/backend'
  - 'gcr.io/$PROJECT_ID/frontend'
