services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "${FRONTEND_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:${BACKEND_PORT}
    tty: true
    stdin_open: true
    init: true
    volumes:
      - ./frontend/src:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "${BACKEND_PORT}:8080"
    tty: true
    stdin_open: true
    init: true
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - PYTHONPATH=/app
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    working_dir: /app
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8080 --reload