apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: docubot-service
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/docubot-agent/docubot-repo/frontend
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:8080"

        - name: backend
          image: us-central1-docker.pkg.dev/docubot-agent/docubot-repo/backend
          env:
            - name: PORT
              value: "8080"
