apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: docubot-service
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/docubot-agent/docubot-repo/frontend
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: next_public_api_url
                  key: latest

        - name: backend
          image: us-central1-docker.pkg.dev/docubot-agent/docubot-repo/backend
          env:
            - name: PORT
              value: "8080"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai_api_key
                  key: latest
            - name: LANGCHAIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: langchain_api_key
                  key: latest
            - name: LANGCHAIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: langchain_endpoint
                  key: latest
            - name: LANGCHAIN_PROJECT
              valueFrom:
                secretKeyRef:
                  name: langchain_project
                  key: latest
            - name: LANGCHAIN_TRACING_V2
              valueFrom:
                secretKeyRef:
                  name: langchain_tracing_v2
                  key: latest
            - name: CORS_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: cors_origins
                  key: latest
